package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

// exportToMarkdown exports a session to markdown format
func exportToMarkdown(session *ThinkingSession, includeBranches bool) string {
	var sb strings.Builder

	sb.WriteString("# Sequential Thinking Session\n\n")
	sb.WriteString(fmt.Sprintf("**Session ID:** %s\n", session.ID))
	sb.WriteString(fmt.Sprintf("**Created:** %s\n", session.Created.Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("**Status:** %s\n", session.Status))
	sb.WriteString(fmt.Sprintf("**Quality Score:** %.2f/1.00\n\n", session.QualityScore))

	if len(session.Tags) > 0 {
		sb.WriteString(fmt.Sprintf("**Tags:** %s\n\n", strings.Join(session.Tags, ", ")))
	}

	sb.WriteString("## Problem\n\n")
	sb.WriteString(fmt.Sprintf("%s\n\n", session.Problem))

	if session != nil && len(session.Context) > 0 {
		sb.WriteString("### Context\n\n")
		for key, value := range session.Context {
			sb.WriteString(fmt.Sprintf("- **%s:** %v\n", key, value))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("## Initial Analysis\n\n")
	sb.WriteString(fmt.Sprintf("%s\n\n", session.InitialAnalysis))

	sb.WriteString("## Reasoning Steps\n\n")
	for _, step := range session.Steps {
		sb.WriteString(fmt.Sprintf("### Step %d: %s\n\n", step.Number, step.Type))
		sb.WriteString(fmt.Sprintf("*%s*\n\n", step.Timestamp.Format("2006-01-02 15:04:05")))
		sb.WriteString(fmt.Sprintf("%s\n\n", step.Content))

		if step.ParentStep != nil {
			sb.WriteString(fmt.Sprintf("↳ *Builds on Step %d*\n\n", *step.ParentStep))
		}

		if len(step.Connections) > 0 {
			sb.WriteString("**Connected to steps:** ")
			connections := make([]string, len(step.Connections))
			for i, c := range step.Connections {
				connections[i] = fmt.Sprintf("%d", c)
			}
			sb.WriteString(strings.Join(connections, ", "))
			sb.WriteString("\n\n")
		}

		if step != nil && len(step.Metadata) > 0 {
			sb.WriteString("**Metadata:**\n")
			for key, value := range step.Metadata {
				sb.WriteString(fmt.Sprintf("- %s: %v\n", key, value))
			}
			sb.WriteString("\n")
		}
	}

	if includeBranches && len(session.Branches) > 0 {
		sb.WriteString("## Alternative Branches\n\n")
		for branchID, branch := range session.Branches {
			sb.WriteString(fmt.Sprintf("### Branch: %s\n\n", branchID[:8]))
			sb.WriteString(fmt.Sprintf("**Diverges from Step:** %d\n", branch.FromStep))
			sb.WriteString(fmt.Sprintf("**Created:** %s\n", branch.Created.Format("2006-01-02 15:04:05")))
			sb.WriteString(fmt.Sprintf("**Description:** %s\n\n", branch.AlternativeDesc))

			if len(branch.Steps) > 0 {
				sb.WriteString("#### Branch Steps\n\n")
				for _, step := range branch.Steps {
					sb.WriteString(fmt.Sprintf("%d. **[%s]** %s\n", step.Number, step.Type, step.Content))
				}
				sb.WriteString("\n")
			}
		}
	}

	sb.WriteString("---\n")
	sb.WriteString("*Generated by Sequential Thinking MCP Server*\n")

	return sb.String()
}

// exportToJSON exports a session to JSON format
func exportToJSON(session *ThinkingSession, includeBranches bool) string {
	exportData := map[string]any{
		"id":               session.ID,
		"problem":          session.Problem,
		"context":          session.Context,
		"steps":            session.Steps,
		"created":          session.Created,
		"last_modified":    session.LastModified,
		"current_step":     session.CurrentStep,
		"quality_score":    session.QualityScore,
		"status":           session.Status,
		"tags":             session.Tags,
		"initial_analysis": session.InitialAnalysis,
	}

	if includeBranches {
		exportData["branches"] = session.Branches
	}

	jsonBytes, err := json.MarshalIndent(exportData, "", "  ")
	if err != nil {
		return fmt.Sprintf(`{"error": "Failed to export: %s"}`, err.Error())
	}

	return string(jsonBytes)
}

// exportToText exports a session to plain text format
func exportToText(session *ThinkingSession, includeBranches bool) string {
	var sb strings.Builder

	sb.WriteString("SEQUENTIAL THINKING SESSION\n")
	sb.WriteString("============================\n\n")
	sb.WriteString(fmt.Sprintf("Session ID: %s\n", session.ID))
	sb.WriteString(fmt.Sprintf("Created: %s\n", session.Created.Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("Status: %s\n", session.Status))
	sb.WriteString(fmt.Sprintf("Quality Score: %.2f/1.00\n", session.QualityScore))

	if len(session.Tags) > 0 {
		sb.WriteString(fmt.Sprintf("Tags: %s\n", strings.Join(session.Tags, ", ")))
	}
	sb.WriteString("\n")

	sb.WriteString("PROBLEM\n")
	sb.WriteString("-------\n")
	sb.WriteString(fmt.Sprintf("%s\n\n", session.Problem))

	if session != nil && len(session.Context) > 0 {
		sb.WriteString("CONTEXT\n")
		sb.WriteString("-------\n")
		for key, value := range session.Context {
			sb.WriteString(fmt.Sprintf("%s: %v\n", key, value))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("INITIAL ANALYSIS\n")
	sb.WriteString("----------------\n")
	sb.WriteString(fmt.Sprintf("%s\n\n", session.InitialAnalysis))

	sb.WriteString("REASONING STEPS\n")
	sb.WriteString("---------------\n\n")
	for _, step := range session.Steps {
		sb.WriteString(fmt.Sprintf("Step %d [%s] - %s\n", step.Number, step.Type, step.Timestamp.Format("15:04:05")))
		sb.WriteString(fmt.Sprintf("%s\n", wrapText(step.Content, 80)))

		if step.ParentStep != nil {
			sb.WriteString(fmt.Sprintf("  → Builds on Step %d\n", *step.ParentStep))
		}

		if len(step.Connections) > 0 {
			sb.WriteString(fmt.Sprintf("  → Connected to: %v\n", step.Connections))
		}
		sb.WriteString("\n")
	}

	if includeBranches && len(session.Branches) > 0 {
		sb.WriteString("ALTERNATIVE BRANCHES\n")
		sb.WriteString("--------------------\n\n")
		for branchID, branch := range session.Branches {
			sb.WriteString(fmt.Sprintf("Branch %s (from Step %d)\n", branchID[:8], branch.FromStep))
			sb.WriteString(fmt.Sprintf("%s\n", branch.AlternativeDesc))

			if len(branch.Steps) > 0 {
				for _, step := range branch.Steps {
					sb.WriteString(fmt.Sprintf("  %d. [%s] %s\n", step.Number, step.Type, step.Content))
				}
			}
			sb.WriteString("\n")
		}
	}

	sb.WriteString("---\n")
	sb.WriteString("Generated by Sequential Thinking MCP Server\n")

	return sb.String()
}

// wrapText wraps text at the specified width
func wrapText(text string, width int) string {
	if len(text) <= width {
		return text
	}

	var sb strings.Builder
	words := strings.Fields(text)
	lineLen := 0

	for i, word := range words {
		wordLen := len(word)
		if lineLen+wordLen+1 > width {
			sb.WriteString("\n")
			lineLen = 0
		}
		if i > 0 && lineLen > 0 {
			sb.WriteString(" ")
			lineLen++
		}
		sb.WriteString(word)
		lineLen += wordLen
	}

	return sb.String()
}
