package handlers

import "github.com/bpradana/sequentialthinking/internal/thinking"

var templates = map[string]*thinking.Template{
	"scientific-method": {
		Type:        "scientific-method",
		Name:        "Scientific Method",
		Description: "Systematic approach to problem-solving through observation, hypothesis, and testing",
		Steps: []string{
			"Make an observation about the problem",
			"Ask a question based on the observation",
			"Form a hypothesis - a testable explanation",
			"Make a prediction based on the hypothesis",
			"Test the prediction through analysis or experiment",
			"Analyze the results",
			"Draw conclusions",
			"Communicate findings",
		},
		WhenToUse: "When investigating cause-and-effect relationships or testing theories",
		Example:   "Why does this system fail under load? Hypothesis: Memory leak in worker threads. Test: Monitor memory usage during load test.",
	},
	"five-whys": {
		Type:        "five-whys",
		Name:        "Five Whys",
		Description: "Root cause analysis by repeatedly asking 'why'",
		Steps: []string{
			"State the problem clearly",
			"Ask 'Why does this problem occur?' - answer based on facts",
			"Ask 'Why?' again about the previous answer",
			"Ask 'Why?' a third time",
			"Ask 'Why?' a fourth time",
			"Ask 'Why?' a fifth time",
			"Identify the root cause revealed",
			"Develop countermeasures for the root cause",
		},
		WhenToUse: "When you need to find the root cause of a problem",
		Example:   "Problem: Server crashed. Why? Out of memory. Why? Memory leak. Why? Unclosed connections. Why? Missing cleanup code. Why? Developer unfamiliar with cleanup requirements.",
	},
	"decision-matrix": {
		Type:        "decision-matrix",
		Name:        "Decision Matrix",
		Description: "Weighted evaluation of multiple options against criteria",
		Steps: []string{
			"List all options to be evaluated",
			"Identify evaluation criteria",
			"Assign weights to each criterion (importance)",
			"Score each option against each criterion",
			"Calculate weighted scores (score × weight)",
			"Sum the weighted scores for each option",
			"Compare totals and identify best option",
			"Review and validate the decision",
		},
		WhenToUse: "When choosing between multiple alternatives with several factors to consider",
		Example:   "Choosing a database: criteria = performance (weight 0.4), cost (0.3), ease of use (0.3). Score each database and compare.",
	},
	"swot-analysis": {
		Type:        "swot-analysis",
		Name:        "SWOT Analysis",
		Description: "Analyze Strengths, Weaknesses, Opportunities, and Threats",
		Steps: []string{
			"Identify internal Strengths",
			"Identify internal Weaknesses",
			"Identify external Opportunities",
			"Identify external Threats",
			"Analyze Strength-Opportunity strategies",
			"Analyze Weakness-Opportunity strategies",
			"Analyze Strength-Threat strategies",
			"Analyze Weakness-Threat strategies",
			"Develop action plan",
		},
		WhenToUse: "When evaluating a project, product, or strategic decision",
		Example:   "New product launch: Strengths = unique features; Weaknesses = high cost; Opportunities = market gap; Threats = competitors.",
	},
	"pros-cons": {
		Type:        "pros-cons",
		Name:        "Pros and Cons",
		Description: "Simple listing of advantages and disadvantages",
		Steps: []string{
			"Clearly state the decision or option",
			"List all positive aspects (pros)",
			"List all negative aspects (cons)",
			"Consider the magnitude of each pro/con",
			"Weigh pros against cons",
			"Consider deal-breakers",
			"Make a decision",
		},
		WhenToUse: "For straightforward decisions with clear positive and negative aspects",
		Example:   "Should we migrate to microservices? Pros: scalability, flexibility. Cons: complexity, overhead.",
	},
	"first-principles": {
		Type:        "first-principles",
		Name:        "First Principles Thinking",
		Description: "Break down problems to fundamental truths and reason up",
		Steps: []string{
			"Identify your current assumptions",
			"Break the problem down to fundamental truths",
			"Question each assumption: Is this necessarily true?",
			"Separate facts from assumptions",
			"Start from the fundamental truths",
			"Reason upward to create new solutions",
			"Challenge conventional approaches",
			"Synthesize new understanding",
		},
		WhenToUse: "When conventional thinking hasn't solved the problem or when innovating",
		Example:   "Electric cars: Instead of 'improve gas engine,' ask 'what is needed for transportation?' → store energy + convert to motion.",
	},
	"fishbone": {
		Type:        "fishbone",
		Name:        "Fishbone Diagram (Ishikawa)",
		Description: "Cause-and-effect analysis across multiple categories",
		Steps: []string{
			"Define the problem (head of fish)",
			"Identify major categories (bones): People, Process, Equipment, Materials, Environment, Management",
			"For each category, identify possible causes",
			"For each cause, ask 'why does this happen?'",
			"Drill down to root causes",
			"Identify most likely root causes",
			"Verify with data",
			"Develop solutions",
		},
		WhenToUse: "When analyzing complex problems with multiple potential causes",
		Example:   "Software defects: People = training gaps, Process = no code review, Equipment = slow test environment, etc.",
	},
	"pareto-analysis": {
		Type:        "pareto-analysis",
		Name:        "Pareto Analysis (80/20)",
		Description: "Identify the vital few from the trivial many",
		Steps: []string{
			"List all problems or causes",
			"Measure the impact or frequency of each",
			"Sort by impact (descending)",
			"Calculate cumulative percentage",
			"Identify the top 20% causing 80% of impact",
			"Focus on the vital few",
			"Develop targeted solutions",
			"Monitor results",
		},
		WhenToUse: "When prioritizing which problems or improvements to address first",
		Example:   "Bug fixes: 20% of bug types cause 80% of crashes. Fix those first.",
	},
}
